services:
    admin.page:
        class: Rockbusters\PageBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Page" }
        arguments:
            - ~
            - Rockbusters\PageBundle\Entity\Page
            - ~
        calls:
            - [ setTranslationDomain, [RockbustersPageBundle]]
