rockbusters_em_location:
    path:      /location/{slug}
    defaults:  { _controller: RockbustersEmBundle:Location:show }

rockbusters_em_locations:
    path:      /locations
    defaults:  { _controller: RockbustersEmBundle:Location:index }
    
rockbusters_em_team:
    path:      /team
    defaults:  { _controller: RockbustersEmBundle:TeamMember:index }

rockbusters_em_team_member:
    path:      /team/{slug}
    defaults:  { _controller: RockbustersEmBundle:TeamMember:show }
